import Head from 'next/head';
import { useState, useEffect } from 'react';
import styles from '../styles/Home.module.css';
import Card from '../components/Card';

export default function Home({ posts }) {
	const [postsList, setPostsList] = useState(posts);
	const [viewdItems, setViewdItems] = useState([]);
	let [page, setPage] = useState(1);

	const loadNext = async () => {
		window.scrollTo({
			top: 0,
			left: 0,
			behavior: 'smooth',
		});
		page = page + 1;
		const res = await fetch(
			`https://retrocket.github.io/retrocketeer-api/posts/${page}.json`
		);
		const postsRes = await res.json();

		setPostsList(postsRes);
		setPage(page);
	};
	const loadPrev = async () => {
		window.scrollTo({
			top: 0,
			left: 0,
			behavior: 'smooth',
		});
		if (page > 1) {
			page = page - 1;
		}
		const res = await fetch(
			`https://retrocket.github.io/retrocketeer-api/posts/${page}.json`
		);
		const posts = await res.json();
		setPostsList(posts);
		setPage(page);
	};

	useEffect(() => {
		const items = JSON.parse(localStorage.getItem('postId'));
		setViewdItems(items);
	}, []);

	return (
		<div className={styles.container}>
			<Head>
				<title>Create Next App</title>
				<meta name='description' content='Generated by create next app' />
				<meta name='viewport' content='initial-scale=1, width=device-width' />

				<link rel='icon' href='/favicon.ico' />
			</Head>

			<main className={styles.main}>
				<div className={styles.cardContainer}>
					{postsList.data.map((post) => (
						<Card
							key={post.id}
							id={post.id}
							title={post.title}
							img={post.featured_image_url}
							published_at={post.published_at}
							user={post.user}
						/>
					))}
				</div>

				<div className={styles.paginate}>
					{postsList.links.next_url ? (
						<>
							<button onClick={loadNext}>next</button>

							{page > 1 ? (
								<button onClick={loadPrev}>prev</button>
							) : (
								<button disabled>prev</button>
							)}
						</>
					) : (
						<>
							<button disabled>next</button>
							<button onClick={loadPrev}>prev</button>
						</>
					)}
				</div>

				<div className={styles.recent}>
					<h2>Recently viewd</h2>
					<div className={styles.cardContainer}>
						{viewdItems &&
							viewdItems.map((post) => (
								<Card
									key={post.id}
									id={post.id}
									title={post.title}
									img={post.featured_image_url}
									published_at={post.published_at}
									user={post.user}
								/>
							))}
					</div>
				</div>
			</main>
		</div>
	);
}
export async function getStaticProps() {
	const res = await fetch(
		`https://retrocket.github.io/retrocketeer-api/posts/1.json`
	);
	const posts = await res.json();

	return {
		props: {
			posts,
		},
	};
}
